#!/bin/bash

# Script Name: dws
# Description: show distrowatch distro position for different distros/time frames.
# Author: Harald Hope
SELF_NAME='dws'
SELF_VERSION='1.4.2'
SELF_DATE='2018-10-22'
# License: GPL 3 or later
# Bugs, issues, problems
# Support forums: https://techpatterns.com/forums/forum-33.html
# IRC: irc.oftc.net channel #smxi
# Issues: https://github.com/smxi/dws/issues

## Changes:
# 1.4.2 2018-10-22 - cleaned up -U section
# 1.4.1 2018-10-21 - cleaned up code, refactored, set default to -r 10; added /etc/dws.conf option
# 1.4.0 2018-10-20 - added -r range, shows top or bottom x distros
# 1.3.7 2018-10-19 - distrowatch table syntax change, they added ?frphr query string after distro id
# 1.3.5 2017-08-01 - bug fix, bash changed slightly
# 1.3.4 2013-10-20 - removed deprecated 'seq'; made output less verbose and neater for multiple distros

## user set defaults, change these you want something else here
# distro: any distro you want, no spaces, dash, or /
# case insensitive, sample: dw says: PC-BSD, make: pcbsd
# can also have multiple, comma separated list, no spaces, like:
# DISTROS='opensolaris,openbsd,pcbsd,arch'
DISTROS='debian'
# options: 7 30 (day) - 3 6 12 (month)
# years: 2002-<year before current year>
# sample: TIME_SPAN='2008'
# TIME_SPAN='6'
TIME_SPAN='7'
# range can be +-99
RANGE=10

# set dynamically, do not touch
RANGE_START=0
## do not change anything under this point
B_DEBUG_1='false'
B_DEBUG_2='false'
DW_DATA=''
LINE='------------------------------------------------------------'
TIME_TEXT=''
# get list of | separated years, 2 digit, 2002 to one less than present
YEAR_LAST=$(( $( date +%Y ) - 1 ))
YEARS=$( tr ' ' '|' <<< $( for (( i=2002;i<=$YEAR_LAST;i++));do echo -n "$i ";done | sed 's/\s$//' ) )
# echo $YEARS
B_TTY='false'
if tty >/dev/null;then
	B_TTY='true'
fi
# override defaults here if you want
if [ -f /etc/dws.conf ];then
	source /etc/dws.conf
fi

# error number/extra data
error_handler(){
	local message=''
	case $1 in
		1)	message="Unsupported argument passed to script: -$2"
			;;
		2)	message="For some reason, even though the distro you requested: $DISTROS is listed at distrowatch.com,\nits ranking number is missing. This is probably a bug in $SELF_NAME."
			;;
		3)	message="The distro you requested: $DISTROS - does not appear to be present in \nDistroWatch.com rankings, for the time period: $TIME_TEXT\nThe distro spelling must correspond to what you see in the right column\nranking section (minus any spaces, /, or dashes, case insensitive)."
			;;
		4)	message="Bad value passed to -t: $2 - Supported time spans: Days: 7 30 - Months: 3 6 12\nYears: $YEARS"
			;;
		5)	message="Wget of data failed. Wget error: $2"
			;;
		6)	message="The page data is null but wget reports no errors."
			;;
		7)	message="This action requires root user status."
			;;
		8)	message="The $SELF_NAME autoupdater reports file corruption, no #**EOF**# found in downloaded file.\Something went wrong with your wget download."
			;;
		9)	message="The $SELF_NAME updater reports you don't have permission to carry out the requested file operation.\n(error: $2) This probably means root owns the file or its directory. Check to make sure."
			;;
		10)	message="An unsupported user set value was used for TIME_SPAN: $TIME_SPAN"
			;;
		11)	message="$SELF_NAME is not in your system \$PATH. Unable to update."
			;;
		12)	message="Bad value passed to -r: $2 - Supported ranges: 1 to 99 or -1 to -99"
			;;
		13)	message="Unknonwn error occurred, no results returned! Might be a bug."
			;;
	esac
	echo -e "Error $1: $message"
	exit $1
}

# args: $1 - "$@"
get_options(){
	local opt=''
	while getopts :d:Dhr:t:Uv opt;do
		case $opt in
			d)	DISTROS=$( tr ',' ' ' <<< $OPTARG )
			   RANGE=0
				;;
			D)	B_DEBUG_1='true'
				;;
			h)	show_help
				;;
			r)	if [ -n "$( grep -E '^[-\+]?[1-9][0-9]?$' <<< $OPTARG )" ];then
					RANGE=$OPTARG
				else
					error_handler 12 "$OPTARG"
				fi
				;;
			t)	if [ -n "$( grep -Ei '^(3|6|7|12|30|'$YEARS')$' <<< $OPTARG )" ];then
					TIME_SPAN=$OPTARG
				else
					error_handler 4 "$OPTARG"
				fi
				;;
			U)	self_updater
				;;
			v)	show_version 'opt'
				;;
			*)	error_handler 1 $OPTARG
				;;
		esac
	done
	# +- to get rid of signed integers
	if [ $RANGE -lt 0 ];then
		RANGE_START=100
		RANGE=$((0 - $RANGE))
	else
		RANGE=$(( $RANGE + 0 ))
	fi
}

## Script Main Data Get/Print
get_dw_data(){
	local dw_url='' data_span=''
	
	# null defaults to 7 day
	case $TIME_SPAN in
		3)
			data_span=13
			TIME_TEXT='3 month'
			;;
		6)
			data_span=26
			TIME_TEXT='6 month'
			;;
		7|'') # default to 7 if null and unset in top prefs
			data_span=1
			TIME_TEXT='7 day'
			;;
		12)
			data_span=52
			TIME_TEXT='12 month'
			;;
		30)
			data_span=4
			TIME_TEXT='30 day'
			;;
		# note: using $YEARS doesn't work with ) method, so doing explicit test
		200[2-9]|20[1-9][0-9])
			if [ -n "$( grep -Ei '^('$YEARS')$' <<< $TIME_SPAN )" ];then
				data_span=$TIME_SPAN
				TIME_TEXT="$TIME_SPAN year"
			else
				error_handler 10
			fi
			;;
		*)
			error_handler 10
			;;
	esac
	dw_url="https://distrowatch.com/index.php?dataspan=$data_span"
	if [ "$B_DEBUG_1" == 'true' ];then
		echo $LINE
		echo "Debugger Step 1: pre wget data"
		echo "DISTROS: $DISTROS :: RANGE: $RANGE :: RANGE_START: $RANGE_START"
		echo "TIME_SPAN: $TIME_SPAN :: TIME_TEXT: $TIME_TEXT"
		echo "data_span: $data_span :: download url: $dw_url"
		echo $LINE
	fi
	if [ "$B_DEBUG_2" != 'true' ];then
		DW_DATA="$( wget -qO - $dw_url )" || error_handler 5 "$?"
	else
		DW_DATA="$( cat ~/bin/scripts/dws/data.txt )"
	fi
	DW_DATA="$( grep -iA2 '<th class="phr1">' <<< "$DW_DATA" | grep -vE '^[\-]+$'  )"
	# echo "$DW_DATA"
	# no wget failure, but null data
	if [ -z "$DW_DATA" ];then
		error_handler 6
	fi
}

generate_distro_ranking(){
	local Working_Data='' line_data='' output='' distro='' a_output=()
	local char_count=0 Max_Count=0 counter=0 item_nu=0 
	
	echo "Distrowatch.com $TIME_TEXT rankings:"
	# first get max length of distro name to set printf
	# Max Count is calculated dynamically for non tty
	if [ "$B_TTY" == 'true' ];then
		if [ $RANGE -eq 0 ];then
			for distro in $DISTROS; do
				char_count=$(wc -c <<< $distro)
				if [ "$char_count" -gt "$Max_Count" ];then
					Max_Count=$char_count
				fi
			done
			Max_Count=$((Max_Count+6))
		else 
			Max_Count=17
		fi
	fi
	if [ $RANGE -eq 0 ];then
		for distro in $DISTROS; do
			Working_Data=$( grep -iE -B 1 -A 1 "<td class=\"phr2\"><a href=\"$distro(\?[^\"]*)?\">" <<< "$DW_DATA" | grep -iEA 2 "<th class=\"phr1\">[0-9]+</th>" | grep -vE '^[\-]+$' )
			#echo "$Working_Data"
			line_data=$(get_distro_data "$distro")
			a_output[$counter]="$line_data"
			((counter++))
		done
	else
		while [ "$counter" -lt "$RANGE" ];do
			if [ $RANGE_START -eq 100 ];then
				item_nu=$((100 - $RANGE + $counter + 1))
			else
				item_nu=$((1 + $counter))
			fi
			Working_Data=$( grep -iE -A 2 "<th class=\"phr1\">$item_nu</th>" <<< "$DW_DATA" )
			if [ -n "$Working_Data" ];then
				distro=$( grep -iE '<td class="phr2">' <<< "$Working_Data" | sed -E 's/.*<a href="([^"?]+)(\?[^\"]*)?">.*/\1/' )
				line_data=$(get_distro_data "$distro")
				a_output[$counter]="$line_data"
				# echo "$distro: $counter"
				((counter++))
			fi
			if [ $counter -gt $RANGE ];then
				break
			fi
		done
	fi
	if [ "${#a_output[@]}" -gt 0 ];then
		n=${#a_output[@]}
		if [ "$RANGE_START" -eq 100 -a "$RANGE" -gt 0 ];then
			while [ "$n" -gt 0 ]; do
				n=$((n - 1))
				output="$output${a_output[$n]}\n"
			done
		else
			local i=0
			while [ "$i" -lt "$n" ]; do
				output="$output${a_output[$i]}\n"
				((i++))
			done
		fi
		echo -e "$output"
	else
		error_handler 13
	fi
}

# $1 - distro name;
get_distro_data(){
	local distro='' distro_id='' hit_data='' hits='' line_data='' ranking='' status=''
	#echo "$3"
	# <td class=\"phr2\"><a href=\"freebsd?frphr\">FreeBSD</a></td>
	if [ -n "$Working_Data" ];then
		distro=$( grep -iE "<td class=\"phr2\">" <<< "$Working_Data" | sed -E 's|.*>([^<]+)</a></td>|\1|' )
		ranking=$( grep -iE "<th class=\"phr1\">[0-9]+</th>" <<< "$Working_Data" | sed -E 's|.*>([0-9]+)<.*|\1|' )
		hits=$( grep -iE "<td class=\"phr3\".*>" <<< "$Working_Data" | sed -E 's|.*>([0-9]+)<.*|\1|' )
		status=$( grep -iE "<td class=\"phr3\".*>" <<< "$Working_Data" | sed -E 's/.*(aup|alevel|adown)\.png.*/\1/' )
		# then make status nice for printout
		case $status in
			aup) status='+';;
			adown)status='-';;
			alevel)status='~';;
			*)status='';; # required for no match cases
		esac
	fi
	if [ -z "$distro" ];then
		distro=$1
	fi
	# and set the status data
	if [ -n "$hits" ];then
		# note that many gui irc clients make ) stuff into emoticons
		if [ "$B_TTY" == 'true' ];then
			hit_data=" ($hits$status)"
			distro_id="\t[$1]"
		else
			hit_data=" :: $hits$status"
			distro_id=''
			Max_Count=$(wc -c <<< "$distro:")
		fi
	fi
	if [ "$B_DEBUG_1" == 'true' ];then
		echo $LINE
		echo "Debugger Step 2: build item data"
		echo "$1 Working_Data: $Working_Data"
		echo "distro: $distro"
		echo "$1 ranking: $ranking"
		echo "$1 hits: $hits"
		echo "$1 status: $status"
		echo $LINE
	fi
	if [ -z "$Working_Data" ];then
		line_data="$( printf "%-${Max_Count}s%s" "$distro:" "not ranked" )"
	else
		line_data="$( printf "%-${Max_Count}s%s%s" "$distro:" "$ranking$hit_data" "$distro_id" )"
	fi
	echo "$line_data"
}

show_help(){
	echo "$SELF_NAME distrowatch distro position script. Version: $SELF_VERSION
Your default with no options is range: $RANGE - time span: $TIME_SPAN
$LINE
$SELF_NAME script options ( any you want or none, like: $SELF_NAME -d arch -t 3 ):
-d - distrowatch distro as listed in right bar, no spaces, /, or dashes, 
     remove them, ie: PC-BSD must be: pcbsd (upper/lower case doesn't matter)
     Sample: $SELF_NAME -d pcbsd
     You can also check multiple distros, by creating a comma separated list, 
     no spaces: $SELF_NAME -d arch,opensolaris,debian,antix
     -d overrides default range.
-r - report range (+-1-99). Top/bottom x. If negative, starts from 100, if 
     positive, starts from 1. $SELF_NAME without -t or -d defaults to range 10.
     Sample: $SELF_NAME -r 20
-t - time span: 7 30 (days) - Months: 3 6 12 - Years: 2002-$YEAR_LAST
     Sample: $SELF_NAME -t 30
-U - Update script to latest version
-D - show debugging output
-h - help menu
-v - show $SELF_NAME current version
$LINE
Output format:
From yeserday: + = rising; ~ = unchanged; - = falling. Does not show for year
output.
Print Distro Name: [ranking] (hits per day +~-) [working name, what you use for
-d]
$LINE
You can change the script defaults at top of script variable settings to 
what you want, just change the values of these top variables and $SELF_NAME 
will show by default what you want to see with no arguments/options:
DISTROS='debian,ubuntu,arch,antix' # show these distros by default
# or
RANGE=20 # show top 20 distros by default
TIME_SPAN='6' # show last 6 months
$LINE
Some exceptions to -d values:
Debian Edu: -d skolelinux
DragonFly: dragonflybsd
HandyLinux: -d handy
Linux Lite: -d lite
MakuluLinux: -d makulu
MX Linux: -d mx
SparkyLinux: -d sparky
SUSE: -d sle
Ubuntu Christian: -d ubuntuce
"
	exit 0
}

# args: $1 - opt (option fired, exit. Optional)
show_version(){
	echo "Your current $SELF_NAME version is: $SELF_VERSION ($SELF_DATE)"
	if [ "$1" == 'opt' ];then
		exit 0
	fi
}

self_updater(){
	local self_location=$( which $SELF_NAME )
	local self_owner=$( ls -l $self_location | awk '{print $3}' )
	local download_url="https://smxi.org/$SELF_NAME"
	local self_data='' new_version='' new_date=''
	local self_user=$( whoami )
	
	if [ -n "$self_location" ];then
		# check for root. Note that if parent dir is owned by root
		# if you try to mv a file to that dir, it will require root
		# permissions as well, even if the file is owned by user.
		if [ "$self_user" != "root" -a "$self_owner" == 'root' ] || \
		 [ "$self_user" != "root" -a "$self_owner" != "$self_user" ];then
			error_handler 7
		fi
		echo $LINE
		show_version 'update'
		echo $LINE
		echo "Starting $SELF_NAME self updater."
		echo "Current version: $SELF_VERSION ($SELF_DATE)"
		# note that || case can't be in subshell...
		self_data="$( wget -qO - $download_url )" || error_handler 5 "$?"
		# try it again just in case it fails
		if [ -z "$( grep '#\*\*EOF\*\*#' <<< "$self_data" )" ];then
			echo "First download attempt failed, trying it again..."
			echo
			self_data="$( wget -qO - $download_url )" || error_handler 5 "$?"
		fi
		# echoing the file data to the user owned file works but stops
		# or damages script execution, so a restart didn't work right.
		if [ -n "$( grep '#\*\*EOF\*\*#' <<< "$self_data" )" ];then
			echo "$self_data" > $self_location || error_handler 9 "echo: $?"
			chmod +x $self_location || error_handler 9 "chmod: $?"
			new_date=$( awk -F '=' '/^SELF_DATE/ {gsub("\047","",$2);print $2;exit;}' $self_location)
			new_version=$( awk -F '=' '/^SELF_VERSION/{gsub("\047","",$2);print $2;exit;}' $self_location)
			echo $LINE
			echo "Success! Restart $SELF_NAME to run updated version: $new_version ($new_date)"
			exit 0
		else
			error_handler 8
		fi
	else
		error_handler 11
	fi
}

## Execute
get_options "$@"
get_dw_data
generate_distro_ranking

exit 0
###**EOF**###
